version: "3"
services:
  ontodia: #ping -w3 192.168.130.3/24
    #command: "SPARQL_ENDPOINT=http://localhost:9999/blazegraph/namespace/kb/sparql npm start"
    depends_on:
      - blazegraph
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: ontodia
    container_name: ontodia
    ports:
      - "5000:5000"

  blazegraph:
    image: metaphacts/blazegraph-basic:latest
    hostname: blazegraph
    container_name: blazegraph
    ports:
      - "9999:8080"
